name: API CI
on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
    unit-tests:
      runs-on: ubuntu-latest

      services:
        mongodb:
          image: mongo:latest
          ports:
            - 27017:27017
          env:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
          options: >-
            --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })' --quiet"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Use Node.js 18.x
          uses: actions/setup-node@v2
          with:
            node-version: 18.x
            cache: 'npm'
            cache-dependency-path: ./api/package-lock.json
        - name: Install dependencies
          shell: bash
          run: npm ci
        - name: View MongoDB logs
          run: docker logs $(docker ps -q --filter ancestor=mongo:latest)
        - name: Run unit tests
          shell: bash
          env:
            NODE_ENV: test
            DATABASE_URL: mongodb://root:123456@localhost:27017/
            DB_NAME: dbtest
          run: npm run test
