name: API CI
on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Use Node.js 18.x
          uses: actions/setup-node@v2
          with:
            node-version: 18.x
            cache: 'npm'
            cache-dependency-path: ./api/package-lock.json
        - name: Install dependencies
          shell: bash
          run: npm ci
        - name: Run unit tests
          shell: bash
          run: npm run test
