name: API CI
on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api

jobs:
    unit-tests:
      runs-on: ubuntu-latest

      services:
        mongodb:
          image: mongo
          ports:
            - 27017:27017
          env:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
            MONGO_INITDB_DATABASE: dbtest
          options: >-
            --health-cmd mongo
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Use Node.js 18.x
          uses: actions/setup-node@v2
          with:
            node-version: 18.x
            cache: 'npm'
            cache-dependency-path: ./api/package-lock.json
        - name: Install dependencies
          shell: bash
          run: npm ci
        - name: Wait for MongoDB to be ready
          shell: bash
          run: |
            echo "Waiting for MongoDB to be ready..."
            while ! echo exit | mongo --host localhost --port 27017 --username root --password 123456 --authenticationDatabase admin; do
              sleep 2
            done
            echo "MongoDB is ready."
        - name: Run unit tests
          shell: bash
          env:
            NODE_ENV: test
            MONGODB_URL_TEST: mongodb://root:123456@localhost:27017/
            MONGODB_DBNAME_TEST: dbtest
          run: npm run test
